# Generated by Django 5.1.5 on 2026-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoDeExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Describe el problema que tenían y cómo lo resolvieron')),
                ('metrica_1_valor', models.CharField(blank=True, help_text='Ej: +65%', max_length=30)),
                ('metrica_1_label', models.CharField(blank=True, help_text='Ej: Reducción de costos operativos', max_length=60)),
                ('metrica_2_valor', models.CharField(blank=True, max_length=30)),
                ('metrica_2_label', models.CharField(blank=True, max_length=60)),
                ('metrica_3_valor', models.CharField(blank=True, max_length=30)),
                ('metrica_3_label', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='casos/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caso de Éxito',
                'verbose_name_plural': 'Casos de Éxito',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('servicio_interes', models.CharField(blank=True, choices=[('automatizacion', 'Automatización de Procesos'), ('dashboard', 'Dashboard / BI'), ('software', 'Software a Medida'), ('consultoria', 'Consultoría Tecnológica'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas privadas del equipo (no visibles para el cliente)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead / Contacto',
                'verbose_name_plural': 'Leads / Contactos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(help_text='Una línea que resume el servicio (aparece en la card)', max_length=200)),
                ('descripcion_larga', models.TextField(blank=True, help_text='Descripción detallada (opcional, para modal o página de detalle)')),
                ('icono', models.CharField(choices=[('chart-bar', '📊 Analytics / Dashboard'), ('cog', '⚙️ Automatización'), ('device-mobile', '📱 App / Software'), ('database', '🗄️ Base de Datos'), ('lightning-bolt', '⚡ Optimización'), ('presentation-chart-line', '📈 Consultoría'), ('cube', '🧩 Integración'), ('shield-check', '🛡️ Seguridad')], default='cog', max_length=50)),
                ('beneficio_clave', models.CharField(blank=True, help_text="Ej: 'Reduce errores en un 80%'", max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, help_text='Ej: Gerente General', max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, help_text='Ej: Distribuidora, Farmacia...', max_length=100)),
                ('foto', models.ImageField(blank=True, help_text='Foto del cliente (opcional)', null=True, upload_to='testimonios/')),
                ('texto', models.TextField(help_text='El testimonio en sus propias palabras')),
                ('resultado_clave', models.CharField(blank=True, help_text="Ej: '+40% en ventas en 60 días'", max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Los testimonios destacados aparecen primero y más prominentes')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-destacado', 'orden'],
            },
        ),
    ]
