# Generated by Django 5.1.5 on 2026-03-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno del formulario', max_length=150)),
                ('slug', models.SlugField(help_text='URL amigable: diagnostico-empresarial → /formulario/diagnostico-empresarial/', unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción visible para el usuario al inicio del formulario')),
                ('activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Si está activo, este formulario reemplaza el formulario de contacto en la landing page')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FaseFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Texto explicativo que verá el usuario en esta fase')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('icono', models.CharField(blank=True, help_text='Emoji o código de icono (ej: 🏢, 📊)', max_length=10)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='landing.formulario')),
            ],
            options={
                'verbose_name': 'Fase del Formulario',
                'verbose_name_plural': 'Fases del Formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto corto'), ('email', 'Email'), ('tel', 'Teléfono'), ('number', 'Número'), ('textarea', 'Texto largo'), ('select', 'Lista desplegable'), ('radio', 'Opción única (radio)'), ('checkbox', 'Opción múltiple (checkbox)'), ('date', 'Fecha')], default='text', max_length=20)),
                ('etiqueta', models.CharField(help_text='Texto del label visible', max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('texto_ayuda', models.CharField(blank=True, help_text='Texto de ayuda debajo del campo', max_length=300)),
                ('requerido', models.BooleanField(default=True)),
                ('opciones', models.TextField(blank=True, help_text='Solo para select/radio/checkbox. Una opción por línea.')),
                ('ancho', models.CharField(choices=[('full', 'Ancho completo (100%)'), ('half', 'Medio ancho (50%)')], default='full', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('condicion_valor', models.CharField(blank=True, help_text='Valor exacto que debe tener la respuesta de la pregunta condicional', max_length=200)),
                ('condicion_pregunta', models.ForeignKey(blank=True, help_text='Mostrar esta pregunta solo si la respuesta a OTRA pregunta cumple una condición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='landing.preguntaformulario')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='landing.faseformulario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SesionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_actual', models.PositiveSmallIntegerField(default=1)),
                ('completado', models.BooleanField(default=False)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='landing.formulario')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_formulario', to='landing.lead')),
            ],
            options={
                'verbose_name': 'Sesión / Respuesta Recibida',
                'verbose_name_plural': 'Sesiones / Respuestas Recibidas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='landing.preguntaformulario')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='landing.sesionformulario')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('sesion', 'pregunta')},
            },
        ),
    ]
