# Generated by Django 5.1.5 on 2026-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='SmartSolutions VE', max_length=100)),
                ('slogan', models.CharField(default='Procesos Alineados, Decisiones Inteligentes', max_length=200)),
                ('descripcion_corta', models.TextField(default='Transformamos PYMEs venezolanas con tecnología, automatización y estrategia de datos.', max_length=300)),
                ('email_contacto', models.EmailField(default='contacto@smartsolutions.com.ve', max_length=254)),
                ('whatsapp_numero', models.CharField(default='+58 412 0000000', help_text='Formato: +58XXXXXXXXXX (sin espacios para el link)', max_length=20)),
                ('whatsapp_mensaje', models.CharField(default='Hola, me interesa conocer más sobre sus servicios.', help_text='Mensaje pre-cargado al hacer clic en el botón de WhatsApp', max_length=300)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('meta_titulo', models.CharField(default='SmartSolutions VE | Consultoría Tecnológica para PYMEs', max_length=70)),
                ('meta_descripcion', models.CharField(default='Ayudamos a PYMEs venezolanas a crecer con automatización, datos y tecnología a medida.', max_length=160)),
                ('hero_titulo_principal', models.CharField(default='Aumenta la Rentabilidad de tu PYME', max_length=100)),
                ('hero_titulo_acento', models.CharField(default='en 90 días o menos', max_length=60)),
                ('hero_subtitulo', models.TextField(default='Sin datos confiables, cada decisión es una apuesta. Te ayudamos a convertir la incertidumbre en crecimiento predecible.', max_length=300)),
                ('metrica_1_valor', models.CharField(default='+50', max_length=20)),
                ('metrica_1_label', models.CharField(default='PYMEs transformadas', max_length=50)),
                ('metrica_2_valor', models.CharField(default='+200%', max_length=20)),
                ('metrica_2_label', models.CharField(default='Mejora en eficiencia', max_length=50)),
                ('metrica_3_valor', models.CharField(default='90 días', max_length=20)),
                ('metrica_3_label', models.CharField(default='Tiempo al primer resultado', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
